/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('ingredients').del()
  await knex('ingredients').insert([
    {id: 1, name: 'Olive Oil'},
    {id: 2, name: 'Sweet Potatoes'},
    {id: 3, name: 'Smoked Paprika'},
    {id: 4, name: 'Ground Cumin'},
    {id: 5, name: 'Onion'},
    {id: 6, name: 'Carrots'},
    {id: 7, name: 'Celery Stick, Chopped'},
    {id: 8, name: 'Garlic Clove, Crushed'},
    {id: 9, name: 'Chilli Powder'},
    {id: 10, name: 'Oregano'},
    {id: 11, name: 'Tomato Puree'},
    {id: 12, name: 'Red Pepper, Chunks'},
    {id: 13, name: 'Can chopped tomatoes'},
    {id: 14, name: 'Can black beans'},
    {id: 15, name: 'Can kidney beans'},
    {id: 16, name: 'Lime Wedges'},
    {id: 17, name: 'Guacamole'},
    {id: 18, name: 'Rice'},
    {id: 19, name: 'Coriander'},
    {id: 20, name: 'Oil'},
    {id: 21, name: 'Red Onion'},
    {id: 22, name: 'Red Chilli'},
    {id: 23, name: 'Ground coriander'},
    {id: 24, name: 'Sweetcorn'},
    {id: 25, name: 'Bunch coriander, chopped'},
    {id: 26, name: 'Polenta'},
    {id: 27, name: 'Buns'},
    {id: 28, name: 'Salsa'},
    {id: 29, name: 'Salad Leaves'},
    {id: 30, name: 'Eggs'},
    {id: 31, name: 'Milk'},
    {id: 32, name: 'Bread'},
    {id: 33, name: 'Flour'},
    {id: 34, name: 'Butter'},
    {id: 35, name: 'Sugar'},
    {id: 36, name: 'Cheese'},
    {id: 37, name: 'Chicken'},
    {id: 38, name: 'Gluten free breadcrumbs'},
    {id: 39, name: 'Mixed Herbs'},
    {id: 40, name: 'BBQ Sauce'},
    {id: 41, name: 'Yeast'},
    {id: 42, name: 'Baking powder'},
    {id: 43, name: 'Beef'},
    {id: 44, name: 'Ham'},
    {id: 45, name: 'Lamb'},
    {id: 46, name: 'Pork'},
    {id: 47, name: 'Beef mince'},
    {id: 48, name: 'Vegetable oil'},
    {id: 49, name: 'Burger buns'},
    {id: 50, name: 'Tomato'},
    {id: 51, name: 'Beetroot'},
    {id: 52, name: 'Horesradish sauce'},
    {id: 53, name: 'Mayonnaise'},
    {id: 54, name: 'Tomato ketchup'},
    {id: 55, name: 'Iceburg lettuce'},
    {id: 56, name: 'Rocket'},
    {id: 57, name: 'Watercress'},
    {id: 58, name: 'Salt'},
    {id: 59, name: 'Pepper'},
    {id: 60, name: 'Beef Stock'},
    {id: 61, name: 'Low Fodmap Beef Stock'},
    {id: 62, name: 'Vegetable Stock'},
    {id: 63, name: 'Low Fodmap Vegetable Stock'},
    {id: 64, name: 'Vegetable Oil'},
    {id: 65, name: 'Plant Based Butter'},
    {id: 66, name: 'Oat Milk'},
    {id: 67, name: 'Almond Milk'},
    {id: 68, name: 'Cocunut Milk'},
    {id: 69, name: 'Gluten free bread'},
    {id: 70, name: 'Gluten free flour'},
    {id: 71, name: 'Gluten free baking powder'},
    {id: 72, name: 'Low fodmap onion replacement powder'},
    {id: 73, name: 'Low fodmap garlic replacement powder'},
    {id: 74, name: 'Spaghetti'},
    {id: 75, name: 'Gluten free Spaghetti'},
    {id: 76, name: 'Pasta'},
    {id: 77, name: 'Gluten free Pasta'},
    {id: 78, name: 'Potato\'s'},
    {id: 79, name: 'Lemon Juice'},
  ]);

  await knex.raw('select setval(\'ingredients_id_seq\', max(id)) from ingredients');
};
