/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('recipe_ingredients').del()
  await knex('recipe_ingredients').insert([
    {id: 1, recipeId: 1, ingredientId: 1, amount: 3, amount_type: 'tbsp'},
    {id: 2, recipeId: 1, ingredientId: 2, amount: 2, amount_type: ''},
    {id: 3, recipeId: 1, ingredientId: 3, amount: 2, amount_type: 'tsp'},
    {id: 4, recipeId: 1, ingredientId: 4, amount: 2, amount_type: 'tsp'},
    {id: 5, recipeId: 1, ingredientId: 5, amount: 1, amount_type: ''},
    {id: 6, recipeId: 1, ingredientId: 6, amount: 2, amount_type: ''},
    {id: 7, recipeId: 1, ingredientId: 7, amount: 2, amount_type: ''},
    {id: 8, recipeId: 1, ingredientId: 8, amount: 2, amount_type: ''},
    {id: 9, recipeId: 1, ingredientId: 9, amount: 2, amount_type: 'tsp'},
    {id: 10, recipeId: 1, ingredientId: 10, amount: 1, amount_type: 'tsp'},
    {id: 11, recipeId: 1, ingredientId: 11, amount: 1, amount_type: 'tbsp'},
    {id: 12, recipeId: 1, ingredientId: 12, amount: 1, amount_type: ''},
    {id: 13, recipeId: 1, ingredientId: 13, amount: 400, amount_type: 'grams'},
    {id: 14, recipeId: 1, ingredientId: 13, amount: 400, amount_type: 'grams'},
    {id: 15, recipeId: 1, ingredientId: 14, amount: 400, amount_type: 'grams'},
    {id: 16, recipeId: 1, ingredientId: 15, amount: 400, amount_type: 'grams'}, 
    {id: 17, recipeId: 1, ingredientId: 16, amount: 1, amount_type: ''},
    {id: 18, recipeId: 1, ingredientId: 17, amount: 1, amount_type: ''},
    {id: 19, recipeId: 1, ingredientId: 18, amount: 1, amount_type: ''},
    {id: 20, recipeId: 1, ingredientId: 19, amount: 1, amount_type: ''},
    {id: 21, recipeId: 2, ingredientId: 2, amount: 1.5, amount_type: 'kg'},
    {id: 22, recipeId: 2, ingredientId: 20, amount: 2, amount_type: 'tsp'},
    {id: 23, recipeId: 2, ingredientId: 21, amount: 2, amount_type: ''},
    {id: 24, recipeId: 2, ingredientId: 22, amount: 2, amount_type: ''},
    {id: 25, recipeId: 2, ingredientId: 4, amount: 1, amount_type: 'tbsp'},
    {id: 26, recipeId: 2, ingredientId: 19, amount: 1, amount_type: 'tbsp'},
    {id: 27, recipeId: 2, ingredientId: 24, amount: 340, amount_type: 'grams'},
    {id: 28, recipeId: 2, ingredientId: 25, amount: 1, amount_type: ''},
    {id: 29, recipeId: 2, ingredientId: 26, amount: 200, amount_type: 'grams'},
    {id: 30, recipeId: 2, ingredientId: 27, amount: 1, amount_type: ''},
    {id: 31, recipeId: 2, ingredientId: 28, amount: 1, amount_type: ''},
    {id: 32, recipeId: 2, ingredientId: 5, amount: 1, amount_type: ''},
    {id: 33, recipeId: 2, ingredientId: 29, amount: 1, amount_type: ''},
    {id: 34, recipeId: 3, ingredientId: 36, amount: 50, amount_type: 'grams'},
    {id: 35, recipeId: 3, ingredientId: 32, amount: 2, amount_type: 'slices'},
    {id: 36, recipeId: 3, ingredientId: 34, amount: 5, amount_type: 'grams'},
    {id: 37, recipeId: 4, ingredientId: 5, amount: 1, amount_type: 'small'},
    {id: 38, recipeId: 4, ingredientId: 47, amount: 500, amount_type: 'grams'},
    {id: 39, recipeId: 4, ingredientId: 30, amount: 1, amount_type: 'large'},
    {id: 41, recipeId: 4, ingredientId: 48, amount: 1, amount_type: 'tbsp'},
    {id: 42, recipeId: 4, ingredientId: 49, amount: 4, amount_type: ''},
    {id: 43, recipeId: 4, ingredientId: 50, amount: 2, amount_type: 'sliced'},
    {id: 44, recipeId: 4, ingredientId: 51, amount: 2, amount_type: 'sliced'},
    {id: 45, recipeId: 4, ingredientId: 52, amount: 1, amount_type: 'tsp'},
    {id: 46, recipeId: 4, ingredientId: 53, amount: 1, amount_type: 'tsp'},
    {id: 47, recipeId: 4, ingredientId: 54, amount: 2, amount_type: 'tsp'},
    {id: 48, recipeId: 4, ingredientId: 55, amount: 1, amount_type: 'handful'},
    {id: 49, recipeId: 4, ingredientId: 56, amount: 1, amount_type: 'handful'},
    {id: 50, recipeId: 4, ingredientId: 57, amount: 1, amount_type: 'handful'},
    {id: 51, recipeId: 5, ingredientId: 37, amount: 1, amount_type: 'breast'},
    {id: 52, recipeId: 5, ingredientId: 38, amount: 30, amount_type: 'grams'},
    {id: 53, recipeId: 5, ingredientId: 30, amount: 1, amount_type: 'large'},
    {id: 54, recipeId: 5, ingredientId: 40, amount: 1, amount_type: 'teaspoon'},
    {id: 55, recipeId: 6, ingredientId: 75, amount: 75, amount_type: 'grams per person'},
    {id: 56, recipeId: 6, ingredientId: 47, amount: 500, amount_type: 'grams'},
    {id: 57, recipeId: 6, ingredientId: 11, amount: 200, amount_type: 'grams'},
    {id: 58, recipeId: 6, ingredientId: 13, amount: 800, amount_type: 'grams'},
    {id: 59, recipeId: 6, ingredientId: 39, amount: 1, amount_type: 'tablespoon'},
    {id: 60, recipeId: 6, ingredientId: 58, amount: 1, amount_type: 'pinch'},
    {id: 61, recipeId: 6, ingredientId: 59, amount: 1, amount_type: 'pinch'},
    {id: 62, recipeId: 6, ingredientId: 61, amount: 250, amount_type: 'ml'},
    {id: 63, recipeId: 6, ingredientId: 72, amount: 1, amount_type: 'teaspoon'},
    {id: 64, recipeId: 6, ingredientId: 73, amount: 1, amount_type: 'teaspoon'},
    {id: 65, recipeId: 6, ingredientId: 6, amount: 1, amount_type: 'large'},
    {id: 66, recipeId: 6, ingredientId: 64, amount: 1, amount_type: 'tablespoon'},
    {id: 67, recipeId: 7, ingredientId: 6, amount: 200, amount_type: 'grams'},
    {id: 68, recipeId: 7, ingredientId: 78, amount: 300, amount_type: 'grams'},
    {id: 69, recipeId: 7, ingredientId: 63, amount: 750, amount_type: 'ml'},
    {id: 70, recipeId: 7, ingredientId: 64, amount: 1, amount_type: 'tbsp'},
    {id: 71, recipeId: 7, ingredientId: 58, amount: 1, amount_type: 'pinch'},
    {id: 72, recipeId: 7, ingredientId: 59, amount: 1, amount_type: 'pinch'},
    {id: 73, recipeId: 7, ingredientId: 72, amount: 1, amount_type: 'tsp'},
    {id: 74, recipeId: 7, ingredientId: 73, amount: 1, amount_type: 'tsp'},
    {id: 75, recipeId: 8, ingredientId: 70, amount: 150, amount_type: 'grams'},
    {id: 76, recipeId: 8, ingredientId: 30, amount: 1, amount_type: 'large'},
    {id: 77, recipeId: 8, ingredientId: 66, amount: 125, amount_type: 'ml'},
    {id: 78, recipeId: 8, ingredientId: 79, amount: 1, amount_type: 'splash per pancake'},
    {id: 79, recipeId: 8, ingredientId: 35, amount: 1, amount_type: 'tsp per pancake'},
    {id: 80, recipeId: 8, ingredientId: 65, amount: 1, amount_type: 'knob'},
  ]);

  await knex.raw('select setval(\'recipe_ingredients_id_seq\', max(id)) from recipe_ingredients');
};
