# Set the project name
name: recipe-finder

services:
  api:
    image: node:latest
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
        restart: true
    working_dir: /app
    volumes:
     - ./:/app
    environment:
     - DB_HOST=localhost
     - DB_PORT=5432
     - DB_NAME=recipefinder
     - DB_USER=rfdbuser
     - DB_PASS=S3cret
     - JWT_TOKEN_SECRET=S3cret
     - JWT_REFRESH_TOKEN_SECRET=S3cret
     - ENVIRONMENT=development
    command: bash -c "npm ci && npm run dev"

  db:
    image: postgres:14-alpine
    ports: 
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=rfdbuser
      - POSTGRES_DB=recipefinder
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'db_prod']
      interval: 30s
      retries: 5
      start_period: 80s