# Set the project name
name: recipe-finder

services:
  db:
    image: postgres:14-alpine
    ports: 
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=rfdbuser
      - POSTGRES_DB=recipefinder